In [8]:
import numpy as np
from sklearn import datasets
from sklearn import tree
import matplotlib.pyplot as plt
from utils import plot_decision_regions

In [7]:
ds = datasets.load_iris()
X,y = ds.data, ds.target
print(X[0:2], y[0:2])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]] [0 0]


In [17]:
np.random.seed(0) # SE USA ESE SEED CUANDO QUIERO HACER OPERACIONES RANDOM
indexes = np.random.permutation(len(X)) # Reordenar los indices
print(indexes[0:2])

[114  62]


In [20]:
# No puedo usar el shuffle por que es un array de 2 dimensiones
X = X[indexes]
y = y[indexes]
print(X[0:2], y[0:2])

[[6.7 3.1 4.7 1.5]
 [6.4 3.1 5.5 1.8]] [1 2]


In [22]:
# extrayendo un porcentaje para train y otro para test
train_percent = 0.8
train_limit = int(len(X)*train_percent)
X_train = X[0:train_limit]
X_test = X[train_limit:]
Y_train = y[0:train_limit]
Y_test = y[train_limit:]

In [28]:
clf = tree.DecisionTreeClassifier(criterion="entropy", max_depth=2)
clf.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=2,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [30]:
# Haciendo Pruebas
res = clf.predict(X_test)
print("Obtenido")
print(res)
print("Esperado")
print(Y_test)
accuracy = clf.score(X_test, Y_test)
print(accuracy)

Obtenido
[0 1 2 0 0 1 1 2 1 2 0 1 0 1 0 0 0 1 0 0 2 2 1 0 1 0 2 1 1 0]
Esperado
[0 1 1 0 0 1 1 2 1 2 0 1 0 2 0 0 0 1 0 0 2 2 1 0 1 0 2 1 1 0]
0.9333333333333333


In [33]:
# Arbol mas elaborado
import graphviz
dot_data = tree.export_graphviz(clf, out_file=None)
graph = graphviz.Source(dot_data)
graph.render("iris")

ExecutableNotFound: failed to execute ['dot', '-Tpdf', '-O', 'iris'], make sure the Graphviz executables are on your systems' PATH